### ISSUE TITLE
[BUG] Pasting in the editor doesn't always paste in the correct spot

### ISSUE THREAD

**Issue by Cytruss-fruit** [DPS2004/Beatblock-issues#176]
**Describe the bug**
Pasting in the editor is sometimes inconstant. This gets particularly annoying whenever you have to do multiple copy-paste's in a row (ie to create a pattern)

**To Reproduce**
1. Go to the editor
2. Shift + double click to select some notes (particularly a selection of notes on smaller beat subdivisions)
3. Ctrl + C to copy
4. Shift + click to select the spot for the notes to be pasted
5. Ctrl + V to paste

**Expected behavior**
Notes are pasted starting at the selected beat.

**Screenshots**
Video of this happenning
https://github.com/user-attachments/assets/ca7f35c9-f81b-4f58-85cd-e51dd89cbacf

**Additional context**
As mentioned, this happens a lot more often if the original selection, begins on a smaller beat subdivision (i.e. on the 3/4th of a beat). I find that the smaller the subdivision the more often this happens, which leads me to believe it could be related to floating point imprecision.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by astrob4t** [comment]
In that video you moved your mouse was slightly closer to the subdivision you placed it at when the game registered your `ctrl+v`, on smaller subdivisions this makes sense to happen because there is a smaller distance between each subdivision so you are more likely to have your mouse closer to the wrong beat, I would say to either A) Use lower dpi when copying and pasting, or B) Try to stop your mouse and make sure its in the right place when pasting.
