### ISSUE TITLE
More depth to the 2 keys 

### ISSUE THREAD

**Issue by B1rb3** [DPS2004/Beatblock-issues#95]
So in beatblock the 2 keys are used to press taps on timing (Z&X for this example). I have played many custom songs that do not require quick enough taps for 2 keys to be necessary, after all, if it would be frequent enough for 2 keys to be a necessity, it wouldn’t be that fun of an experience. Throwing away this feature would be a waste, so how about we add variations in the tap note instead?  There could be notes that requires both keys to actually tap them, or/and individual taps for each key. This is more focused on more difficult levels since I can imagine how much processing in the brain has to be done for 2 individual taps.

**Comment by OblivionCreator** [comment]
Hi,

There are currently no plans to add specific requirements to the keys.
The current two-tap key implementation is due to an engine limitation which causes keypresses to be ignored if that input is already being held down.

Having two tap inputs for this works nicely, as it means you can alternate easily (either via Z&X or via space&shift or even via mosue1&mouse2) without risking any key overlap.

We would like to keep taps as simple and as intuitive as possible, which is why they are a one-button solution.
